name: Create Weekly Reflection
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
      inputs:
        startdate:
          description: 'Start date (YYYY-MM-DD)'
          required: false
        enddate:
          description: 'End date (YYYY-MM-DD)'
          required: false
jobs:
  create_issue:
    name: Create reflection issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_REFLECTION_PAT }}
      - name: Create an issue via an action
        run: |
          BODY=$(cat .github/content-templates/reflection.md)

          if [ -z "$STARTDATE" ]; then
            # Get the Monday of this week
            STARTDATE=$(date -d "monday this week" "+%B %d")
          fi
          if [ -z "$ENDDATE" ]; then
            # Get the Friday of this week
            ENDDATE=$(date -d "friday this week" "+%B %d, %Y")
          fi

          gh issue create \
            --title "Reflection: $STARTDATE - $ENDDATE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_REFLECTION_PAT }}
          GH_REPO: ${{ github.repository }}
          ASSIGNEES: ${{ github.repository_owner }}
          LABELS: reflection
          STARTDATE: ${{ github.event.inputs.startdate }}
          ENDDATE: ${{ github.event.inputs.enddate }}
